pull_request_rules:
  - name: automatic merge for dependeabot
    conditions:
      - and:
          - "author=dependabot[bot]"
          - or:
              - "title~=Bump super-pom from"
              - "title~=Bump super-version from"
    actions:
      merge:
        method: rebase
