# 执行这个 Actions 可以发布代码带中央仓库
name: deploy

on:
  workflow_dispatch:

  release:
    types:
      - created
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build
        run: mvn -B clean package

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '8'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn clean deploy -Dgpg.skip=false
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
